applicationName: abacus

image:
  name: ghcr.io/imo-soft/abacus
  tag: latest
  imagePullSecrets:
    name: docker-registry
  pullPolicy: IfNotPresent

deployment:
  replicas: 1
  revisionHistoryLimit: 3
  containerPort: 80
  resources:
    enabled: true
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 20m
      memory: 20Mi
  healthChecks:
    enabled: true
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80

service:
  type: NodePort
  servicePort: 80
  portName: http

ingress:
  fqdn: abacus.local
  tls:
    enable: false
    secretName: abacus-tls-secret

hpa:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 75
    targetMemoryUtilization: 75
    # behavior:
    #   ScaleUp:
    #   ScaleDown:

pdb:
  maxUnavailable: 1

secrets:
  enabled: false
  refreshInterval: 5m
  secretStoreRef: hashicorp-vault-store-production
  dataFrom:
    - extract:
        key: abacus

configmap:
  enabled: false
  data: []