applicationName: abacus
# namespace: production

deployment:
  image:
    repository: ghcr.io/imo-soft/abacus.git
    tag: 1.9.8
  replicas: 1
  revisionHistoryLimit: 3
  resources:
    enabled: true
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 20m
      memory: 20Mi
  healthChecks:
    enabled: true
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
  imagePullSecrets:
    name: docker-registry

service:
  loadBalancerIP: 127.0.0.1

ingress:
  fqdn: abacus.it-outsource.me

hpa:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilization: 40
    targetMemoryUtilization: 40
    # behavior:
    #   ScaleUp:
    #   ScaleDown:

pdb:
  maxUnavailable: 1
