apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abacus
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: abacus.it-outsource.me
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: abacus
              port:
                number: 80
