apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  {{- if .Values.service.metadata_annotations }}
  {{- if .Values.service.metadata_annotations.enabled}}
  annotations:
    {{- toYaml .Values.service.metadata_annotations.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.servicePort }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
