apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  {{- if .Values.pdb }}
  {{- toYaml .Values.pdb | nindent 2 }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}