apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    app: {{ .Values.applicationName }}
  ports:
  - port: 80
