apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.servicePort }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
