version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-cli: circleci/aws-cli@1.4.1
  # aws-eks: circleci/aws-eks@1.0.3
  docker: circleci/docker@1.5.0
  # kubernetes: circleci/kubernetes@0.11.2

parameters:
  service-name:
    type: string
    default: "abacus"

#
# Commands can be called as steps in any job(s) of this config.
#
# @doc https://circleci.com/docs/2.0/reusing-config/#the-commands-key
#
commands:

  export-docker-tag:
    steps:
      - run:
          name: Export docker tag
          command: |
            DOCKER_TAG=""
            branch="${CIRCLE_BRANCH//[\/:\{\}\[\]]/-}"
            commit=$(echo $CIRCLE_SHA1 | cut -c -7)
            version="${CIRCLE_TAG}"

            case "$CIRCLE_BRANCH" in
              main | master ) branch_short="prod" ;;
              develop ) branch_short="dev" ;;
              *) branch_short=$branch ;;
            esac

            if [ -z "${version}" ]; then
                echo "export DOCKER_TAG=${branch_short}-${CIRCLE_BUILD_NUM}" >> $BASH_ENV
            else
                echo "export DOCKER_TAG=${version}" >> $BASH_ENV
            fi

#
# Jobs presents building blocks of CI/CD applications.
#
# @doc https://circleci.com/docs/2.0/concepts/#jobs
#
jobs:
  build-test:
    machine: true
    steps:
      - export-docker-tag
      - checkout
      - aws-ecr/build-image:
          dockerfile: Dockerfile
          push-image: false
          repo: << pipeline.parameters.service-name >>
          tag: ${DOCKER_TAG}

  build-test-push:
    machine: true
    steps:
      - export-docker-tag
      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: Dockerfile
          push-image: true
          repo: << pipeline.parameters.service-name >>
          tag: ${DOCKER_TAG}

#
# Workflows can orchestrate jobs, defines run order, dependencies and approval.
#
# @doc https://circleci.com/docs/2.0/concepts/#workflows
#
workflows:
  untagged-develop-build:
    jobs:
      - build-test-push:
          filters:
            branches:
              only:
                - develop

  untagged-master-build:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - master

  tagged-build:
    jobs:
      - build-test-push:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]){1,2}.*/
